package com.thingtrack.workbench.view.drivers;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import org.tepi.filtertable.FilterTable;
import org.tepi.filtertable.datefilter.DateInterval;

import ru.xpoft.vaadin.VaadinView;

import com.google.common.eventbus.Subscribe;
import com.thingtrack.tachoreader.domain.Driver;
import com.thingtrack.tachoreader.service.api.DriverService;
import com.thingtrack.workbench.WorkbenchUI;
import com.thingtrack.workbench.component.AbstractI18NView;
import com.thingtrack.workbench.component.ConfirmForm;
import com.thingtrack.workbench.component.PaginationToolbar;
import com.thingtrack.workbench.component.PaginationToolbar.ClickChangePageSizeListener;
import com.thingtrack.workbench.component.PaginationToolbar.ClickFirstPageListener;
import com.thingtrack.workbench.component.PaginationToolbar.ClickLastPageListener;
import com.thingtrack.workbench.component.PaginationToolbar.ClickNextPageListener;
import com.thingtrack.workbench.component.PaginationToolbar.ClickPreviousPageListener;
import com.thingtrack.workbench.component.PaginationToolbar.PageEvent;
import com.thingtrack.workbench.component.Toolbar;
import com.thingtrack.workbench.component.Toolbar.ClickAddListener;
import com.thingtrack.workbench.component.Toolbar.ClickFilterListener;
import com.thingtrack.workbench.component.Toolbar.ClickRefreshListener;
import com.thingtrack.workbench.component.Toolbar.ClickRemoveListener;
import com.thingtrack.workbench.component.Toolbar.ClickSaveListener;
import com.thingtrack.workbench.component.Toolbar.ClickToolbarEvent;
import com.thingtrack.workbench.component.WindowForm;
import com.thingtrack.workbench.event.DashboardEvent.ProfileUpdatedEvent;
import com.thingtrack.workbench.event.DashboardEventBus;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.data.util.converter.StringToDateConverter;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Field;
import com.vaadin.ui.TableFieldFactory;
import com.vaadin.ui.CustomTable.RowHeaderMode;
import com.vaadin.ui.VerticalLayout;

@Component
@Scope("prototype")
@VaadinView(value=DriverView.NAME, cached=true)
public class DriverView extends AbstractI18NView implements View, 
			ClickAddListener, ClickSaveListener, ClickRemoveListener,
			ClickRefreshListener, ClickChangePageSizeListener, ClickFirstPageListener, ClickPreviousPageListener, 
			ClickNextPageListener, ClickLastPageListener, ClickFilterListener {
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private PaginationToolbar driverPaginationToolbar;

	@AutoGenerated
	private FilterTable driverTable;

	@AutoGenerated
	private Toolbar driverToolbar;

	private static final long serialVersionUID = 1L;
	public static final String NAME = "drivers";
	
	@Autowired
	private DriverService driverService;
	
	private List<Driver> drivers = null;
	private BeanItemContainer<Driver> driverContainer = new BeanItemContainer<Driver>(Driver.class);
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public DriverView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		initialize();    		
	}
	
	private void initialize() {
		// configure filter table
		driverTable.setFilterBarVisible(true);
		driverTable.setSelectable(true);
		driverTable.setImmediate(true);
		driverTable.setMultiSelect(false);
		driverTable.setNullSelectionAllowed(false);
		driverTable.setColumnReorderingAllowed(true); 
		driverTable.setColumnCollapsingAllowed(true);				
		driverTable.setRowHeaderMode(RowHeaderMode.INDEX);
		
		driverTable.setFilterOnDemand(true);
		
		// configure toolbar events
		driverToolbar.addAddListener(this);
		driverToolbar.addSaveListener(this);
		driverToolbar.addRemoveListener(this);
		driverToolbar.addRefreshListener(this);
		driverToolbar.addFilterListener(this);
		
		// configure pagination toolbar events
		driverPaginationToolbar.addClickChangePageSizeListener(this);
		driverPaginationToolbar.addClickFirstPageListener(this);
		driverPaginationToolbar.addClickPreviousPageListener(this);
		driverPaginationToolbar.addClickNextPageListener(this);
		driverPaginationToolbar.addClickLastPageListener(this);
		
		DashboardEventBus.register(this);
	}
	
	@Override
    public void enter(ViewChangeEvent event) {
    }
	
	@SuppressWarnings("serial")
	@PostConstruct
    public void PostConstruct() {        	
    	if (driverService != null) {    		
    		try {    	
    			loadDatasource(driverPaginationToolbar.getPageNumber(), driverPaginationToolbar.getPageSize());
    			    			
    			driverTable.setContainerDataSource(driverContainer);    		
				    			
    			driverTable.setVisibleColumns((Object[]) new String[] { "id", "name", "email", "cardNumber", "cardHolderBirthDate", "cardExpiryDate", "active", "creationDate" } );
    			driverTable.setColumnHeaders(new String[] { "ID", "Name", "Email", "Card Number", "Card Holder Birthdate", "Card Expiry Date", "Active", "Creation Date" } );
				
    			driverTable.setColumnCollapsed("id", true);
    			driverTable.setColumnCollapsed("cardHolderBirthDate", true);
    			driverTable.setColumnCollapsed("cardExpiryDate", true);
    			
    			driverTable.setConverter("cardHolderBirthDate", new StringToDateConverter() {
    			    @Override
    			    protected DateFormat getFormat(Locale locale) {
    			    	/*if (locale == null)
            				locale = Locale.getDefault();        
    			    	
    			    	DateFormat f = DateFormat.getDateTimeInstance(DateFormat.MEDIUM, DateFormat.MEDIUM, locale);
    			        f.setLenient(false);*/
    			        
    			        return new SimpleDateFormat("dd/MM/yyyy");
    			    }
    			});
    			driverTable.setConverter("cardExpiryDate", new StringToDateConverter() {
    			    @Override
    			    protected DateFormat getFormat(Locale locale) {
    			    	return new SimpleDateFormat("dd/MM/yyyy");
    			    }
    			});
    			driverTable.setConverter("creationDate", new StringToDateConverter() {
    			    @Override
    			    protected DateFormat getFormat(Locale locale) {   			        
    			        return new SimpleDateFormat("dd/MM/yyyy HH:mm");
    			    }
    			});
    			driverTable.setEditable(true);
    			driverTable.setTableFieldFactory(new TableFieldFactory() {					
					@Override
					public Field<?> createField(Container container, Object itemId,
							Object propertyId, com.vaadin.ui.Component uiContext) {
						if("active".equals(propertyId))  {
							CheckBox field = new CheckBox();
							field.setReadOnly(true);
							
							return field;
						}
						return null;
					}
				});
    			
    			driverToolbar.setTable(driverTable);		
    			driverToolbar.setDownloadFileName("Drivers");
    			
    			if (driverContainer.size() > 0)
    				driverTable.select(driverContainer.getIdByIndex(0));
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    	}
    }
	
	@Subscribe
    public void updateUserName(final ProfileUpdatedEvent event) {
		if (event != null) {
			refreshButtonClick(null);
		}		
    }
	
	@Override
	public void addButtonClick(ClickToolbarEvent event) {
		// created selected item
		Driver driver = driverService.createNewEntity(WorkbenchUI.getCurrent().getUser());
		
		try {
			@SuppressWarnings({ "unused", "serial" })
			WindowForm<Driver> driverWindow = new WindowForm<Driver>(getI18N().getMessage("com.thingtrack.workbench.view.driver.DriverView.tittle.add"), getI18N(), driver, new DriverForm(), new WindowForm.CloseWindowDialogListener<Driver>() {
				@Override
				public void windowDialogClose(WindowForm<Driver>.CloseWindowDialogEvent<Driver> event) {					
					if (event.getDialogResult() != WindowForm.DialogResult.OK)															
			    		return;					    		
										
					try {			
						Driver driver = event.getDomainEntity();
						driver.setCreatedBy(WorkbenchUI.getCurrent().getUser()); // a bug in JPA
						driver.setCreationDate(new Date());
						
						// insert entity
						driver = driverService.save(driver);
						
						// refresh table
						driverContainer.addBean(driver);
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
			});
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}			
	}
	
	@Override
	public void saveButtonClick(ClickToolbarEvent event) {
		// get selected item
		Driver driver = (Driver) driverTable.getValue();
		
		try {
			@SuppressWarnings({ "unused", "serial" })
			WindowForm<Driver> driverWindow = new WindowForm<Driver>(getI18N().getMessage("com.thingtrack.workbench.view.driver.DriverView.tittle.edit"), getI18N(), driver, new DriverForm(), new WindowForm.CloseWindowDialogListener<Driver>() {
				@Override
				public void windowDialogClose(WindowForm<Driver>.CloseWindowDialogEvent<Driver> event) {					
					if (event.getDialogResult() != WindowForm.DialogResult.OK)															
			    		return;					    		
										
					try {
						// update entity
						Driver driver = (Driver) driverTable.getValue();
						driver.setUpdatedBy(WorkbenchUI.getCurrent().getUser()); // bug JPA
						driver.setUpdatedDate(new Date());
						
						driver = driverService.save(driver);
						
						// refresh table
						driverTable.refreshRowCache();
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
			});
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 		
	}
	
	@SuppressWarnings({ "unused", "rawtypes" })
	@Override
	public void removeButtonClick(ClickToolbarEvent event) {
		@SuppressWarnings("serial")
		ConfirmForm productConfirmForm = new ConfirmForm(getI18N().getMessage("com.thingtrack.workbench.view.driver.DriverView.tittle.remove"), getI18N().getMessage("com.thingtrack.workbench.view.driver.DriverView.question.remove"), new ConfirmForm.CloseConfirmFormListener() {
			@Override
			public void windowDialogClose(ConfirmForm.CloseWindowDialogEvent event) {						
				if (event.getDialogResult() != ConfirmForm.DialogResult.YES)															
		    		return;	
				
				try {
					// remove entity (unset entity)
					Driver driver = (Driver) driverTable.getValue();
					
					driver.setActive(false);
					driverService.save(driver);
					
					// refresh table
					driverTable.refreshRowCache();
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});	
	}
	
	@Override
	public void refreshButtonClick(ClickToolbarEvent event) {
		// recover entity selected before refresh
		Driver driverSelected = (Driver) driverTable.getValue();

		loadDatasource(driverPaginationToolbar.getPageNumber(), driverPaginationToolbar.getPageSize());
								
		// select register in the grid
		if (driverContainer.size() > 0 && driverSelected != null)
			driverTable.select(driverContainer.getItem(driverSelected).getBean());
		else if (driverContainer.size() > 0)
			driverTable.select(driverContainer.getIdByIndex(0));		
	}
	
	@Override
	public void addFilterClick(ClickToolbarEvent event) {
		loadDatasource(driverPaginationToolbar.getPageNumber(), driverPaginationToolbar.getPageSize());
		
	}
	
	@Override
	public void changePageSizeClick(PageEvent event) {
		loadDatasource(event.getPageNumber(), event.getPageSize());
		
	}
	
	@Override
	public void firstPageClick(PageEvent event) {
		loadDatasource(event.getPageNumber(), event.getPageSize());		
	}
	
	@Override
	public void previousPageClick(PageEvent event) {
		loadDatasource(event.getPageNumber(), event.getPageSize());
		
	}
	
	@Override
	public void nextPageClick(PageEvent event) {
		loadDatasource(event.getPageNumber(), event.getPageSize());
		
	}
	
	@Override
	public void lastPageClick(PageEvent event) {
		loadDatasource(event.getPageNumber(), event.getPageSize());
		
	}
		
	private void loadDatasource(int pageNumber, int pageSize) {
		try {
			Integer filterId = null;
			String filterName = null;
			String filterEmail = null;
			String filterCardNumber = null;
			Date filterCardHolderBirthdayFrom = null;
			Date filterCardHolderBirthdayTo = null;
			Date filterCardExpiryDateFrom = null;
			Date filterCardExpiryDateTo = null;
			Date filterCreationDateFrom = null;
			Date filterCreationDateTo = null;
			Boolean filterActive = null;
			
			if (driverTable.getFilterFieldValue("id") != null && !driverTable.getFilterFieldValue("id").equals(""))
				filterId = Integer.parseInt(driverTable.getFilterFieldValue("id").toString());
			if (driverTable.getFilterFieldValue("name") != null && !driverTable.getFilterFieldValue("name").equals(""))
				filterName = driverTable.getFilterFieldValue("name").toString();
			if (driverTable.getFilterFieldValue("email") != null && !driverTable.getFilterFieldValue("email").equals(""))
				filterEmail = driverTable.getFilterFieldValue("email").toString();			
			if (driverTable.getFilterFieldValue("cardNumber") != null && !driverTable.getFilterFieldValue("cardNumber").equals(""))
				filterCardNumber = driverTable.getFilterFieldValue("cardNumber").toString();
			if (driverTable.getFilterFieldValue("cardHolderBirthday") != null && !driverTable.getFilterFieldValue("cardHolderBirthday").equals("")) {
				DateInterval dateInterval = (DateInterval)driverTable.getFilterFieldValue("cardHolderBirthday");
				
				filterCardHolderBirthdayFrom = dateInterval.getFrom();
				filterCardHolderBirthdayTo = dateInterval.getTo();
			}	
			if (driverTable.getFilterFieldValue("cardExpiryDate") != null && !driverTable.getFilterFieldValue("cardExpiryDate").equals("")) {
				DateInterval dateInterval = (DateInterval)driverTable.getFilterFieldValue("cardExpiryDate");
				
				filterCardExpiryDateFrom = dateInterval.getFrom();
				filterCardExpiryDateTo = dateInterval.getTo();
			}			
			if (driverTable.getFilterFieldValue("creationDate") != null && !driverTable.getFilterFieldValue("creationDate").equals("")) {
				DateInterval dateInterval = (DateInterval)driverTable.getFilterFieldValue("creationDate");
				
				filterCreationDateFrom = dateInterval.getFrom();
				filterCreationDateTo = dateInterval.getTo();
			}	
			if (driverTable.getFilterFieldValue("active") != null && !driverTable.getFilterFieldValue("active").equals(""))
				filterActive = Boolean.parseBoolean(driverTable.getFilterFieldValue("active").toString());
			
			// refresh count pages
			driverPaginationToolbar.setTotPages(driverService.getCount(driverPaginationToolbar.getPageSize(), WorkbenchUI.getCurrent().getUser(),
					filterId, filterName, filterEmail, filterCardNumber, filterCardHolderBirthdayFrom, filterCardHolderBirthdayTo,
					filterCardExpiryDateFrom, filterCardExpiryDateTo, 
					filterCreationDateFrom, filterCreationDateTo, filterActive));
			
			// select page registers			
			drivers = driverService.getAll(pageNumber, pageSize, WorkbenchUI.getCurrent().getUser(),
					filterId, filterName, filterEmail, filterCardNumber, filterCardHolderBirthdayFrom, filterCardHolderBirthdayTo,
					filterCardExpiryDateFrom, filterCardExpiryDateTo, 
					filterCreationDateFrom, filterCreationDateTo, filterActive);			

			driverContainer.removeAllItems();
			driverContainer.addAll(drivers);
							
			if (driverContainer.size() > 0)
				driverTable.select(driverContainer.getIdByIndex(0));			
		} catch (Exception e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
}
	@Override
	protected void updateLabels() {
		if (getI18N() != null) {
			driverTable.setColumnHeaders(new String[] { getI18N().getMessage("com.thingtrack.workbench.view.driver.DriverView.driverTable.column.id"),
					  getI18N().getMessage("com.thingtrack.workbench.view.driver.DriverView.driverTable.column.name"),
					  getI18N().getMessage("com.thingtrack.workbench.view.driver.DriverView.driverTable.column.email"),
					  getI18N().getMessage("com.thingtrack.workbench.view.driver.DriverView.driverTable.column.cardNumber"),
					  getI18N().getMessage("com.thingtrack.workbench.view.driver.DriverView.driverTable.column.cardHolderBirthDate"),
					  getI18N().getMessage("com.thingtrack.workbench.view.driver.DriverView.driverTable.column.cardExpiryDate"),
					  getI18N().getMessage("com.thingtrack.workbench.view.driver.DriverView.driverTable.column.active"),
					  getI18N().getMessage("com.thingtrack.workbench.view.driver.DriverView.driverTable.column.creationDate")
					  });
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// agentToolbar
		driverToolbar = new Toolbar();
		driverToolbar.setImmediate(false);
		driverToolbar.setWidth("-1px");
		driverToolbar.setHeight("-1px");
		mainLayout.addComponent(driverToolbar);
		
		// agentTable
		driverTable = new FilterTable();
		driverTable.setImmediate(true);
		driverTable.setWidth("100.0%");
		driverTable.setHeight("100.0%");
		mainLayout.addComponent(driverTable);
		mainLayout.setExpandRatio(driverTable, 1.0f);
		
		// agentPaginationToolbar
		driverPaginationToolbar = new PaginationToolbar();
		driverPaginationToolbar.setImmediate(false);
		driverPaginationToolbar.setWidth("-1px");
		driverPaginationToolbar.setHeight("-1px");
		mainLayout.addComponent(driverPaginationToolbar);
		mainLayout.setComponentAlignment(driverPaginationToolbar,
				new Alignment(6));
		
		return mainLayout;
	}
}
