package com.thingtrack.workbench.view.administrator;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import org.tepi.filtertable.FilterTable;
import org.tepi.filtertable.datefilter.DateInterval;

import ru.xpoft.vaadin.VaadinView;

import com.google.common.eventbus.Subscribe;
import com.thingtrack.tachoreader.domain.Administrator;
import com.thingtrack.tachoreader.service.api.AdministratorService;
import com.thingtrack.workbench.WorkbenchUI;
import com.thingtrack.workbench.component.AbstractI18NView;
import com.thingtrack.workbench.component.ConfirmForm;
import com.thingtrack.workbench.component.PaginationToolbar;
import com.thingtrack.workbench.component.PaginationToolbar.ClickChangePageSizeListener;
import com.thingtrack.workbench.component.PaginationToolbar.ClickFirstPageListener;
import com.thingtrack.workbench.component.PaginationToolbar.ClickLastPageListener;
import com.thingtrack.workbench.component.PaginationToolbar.ClickNextPageListener;
import com.thingtrack.workbench.component.PaginationToolbar.ClickPreviousPageListener;
import com.thingtrack.workbench.component.PaginationToolbar.PageEvent;
import com.thingtrack.workbench.component.Toolbar;
import com.thingtrack.workbench.component.Toolbar.ClickAddListener;
import com.thingtrack.workbench.component.Toolbar.ClickFilterListener;
import com.thingtrack.workbench.component.Toolbar.ClickRefreshListener;
import com.thingtrack.workbench.component.Toolbar.ClickRemoveListener;
import com.thingtrack.workbench.component.Toolbar.ClickSaveListener;
import com.thingtrack.workbench.component.Toolbar.ClickToolbarEvent;
import com.thingtrack.workbench.component.WindowForm;
import com.thingtrack.workbench.event.DashboardEvent.ProfileUpdatedEvent;
import com.thingtrack.workbench.event.DashboardEventBus;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.data.util.converter.StringToDateConverter;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Field;
import com.vaadin.ui.TableFieldFactory;
import com.vaadin.ui.CustomTable.RowHeaderMode;
import com.vaadin.ui.VerticalLayout;

@Component
@Scope("prototype")
@VaadinView(value=AdministratorView.NAME, cached=true)
public class AdministratorView extends AbstractI18NView implements View, 
			ClickAddListener, ClickSaveListener, ClickRemoveListener,
			ClickRefreshListener,
			ClickChangePageSizeListener, ClickFirstPageListener, ClickPreviousPageListener, 
			ClickNextPageListener, ClickLastPageListener, ClickFilterListener {
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private PaginationToolbar administratorPaginationToolbar;

	@AutoGenerated
	private FilterTable administratorTable;

	@AutoGenerated
	private Toolbar administratorToolbar;

	private static final long serialVersionUID = 1L;
	public static final String NAME = "administrators";
	
	@Autowired
	private AdministratorService administratorService;
	
	private List<Administrator> administrators = null;
	private BeanItemContainer<Administrator> administratorContainer = new BeanItemContainer<Administrator>(Administrator.class);
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public AdministratorView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		initialize(); 
	}
	
	private void initialize() {
		// configure filter table
		administratorTable.setFilterBarVisible(true);
		administratorTable.setSelectable(true);
		administratorTable.setImmediate(true);
		administratorTable.setMultiSelect(false);
		administratorTable.setNullSelectionAllowed(false);
		administratorTable.setColumnReorderingAllowed(true); 
		administratorTable.setColumnCollapsingAllowed(true);				
		administratorTable.setRowHeaderMode(RowHeaderMode.INDEX);
		
		administratorTable.setFilterOnDemand(true);
		
		// configure toolbar
		administratorToolbar.addAddListener(this);
		administratorToolbar.addSaveListener(this);
		administratorToolbar.addRemoveListener(this);
		administratorToolbar.addRefreshListener(this);
		administratorToolbar.addFilterListener(this);
		
		// configure paginatin toolbar
		administratorPaginationToolbar.addClickChangePageSizeListener(this);
		administratorPaginationToolbar.addClickFirstPageListener(this);
		administratorPaginationToolbar.addClickPreviousPageListener(this);
		administratorPaginationToolbar.addClickNextPageListener(this);
		administratorPaginationToolbar.addClickLastPageListener(this);
		
		DashboardEventBus.register(this);		
	}
	
	@Override
    public void enter(ViewChangeEvent event) {
    }
	
	@SuppressWarnings("serial")
	@PostConstruct
    public void PostConstruct() {        	
    	if (administratorService != null) {    		
    		try {    	
    			loadDatasource(administratorPaginationToolbar.getPageNumber(), administratorPaginationToolbar.getPageSize());
    			    			
    			administratorTable.setContainerDataSource(administratorContainer);    		
				    			
    			administratorTable.setVisibleColumns((Object[]) new String[] { "id", "name", "email", "active", "creationDate" } );
    			administratorTable.setColumnHeaders(new String[] { "ID", "Name", "Email", "Active", "Creation Date" } );
				
    			administratorTable.setColumnCollapsed("id", true);				    			
    			administratorTable.setConverter("creationDate", new StringToDateConverter() {
    			    @Override
    			    protected DateFormat getFormat(Locale locale) {   			        
    			        return new SimpleDateFormat("dd/MM/yyyy HH:mm");
    			    }
    			});
    			administratorTable.setEditable(true);
    			administratorTable.setTableFieldFactory(new TableFieldFactory() {					
					@Override
					public Field<?> createField(Container container, Object itemId,
							Object propertyId, com.vaadin.ui.Component uiContext) {
						if("active".equals(propertyId))  {
							CheckBox field = new CheckBox();
							field.setReadOnly(true);
							
							return field;
						}
						return null;
					}
				});
    			
    			administratorToolbar.setTable(administratorTable);		
    			administratorToolbar.setDownloadFileName("Administrators");
    			
    			if (administratorContainer.size() > 0)
    				administratorTable.select(administratorContainer.getIdByIndex(0));
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    	}
    }
	
	@Subscribe
    public void updateUserName(final ProfileUpdatedEvent event) {
		if (event != null) {
			refreshButtonClick(null);
		}		
    }
	
	@Override
	public void addButtonClick(ClickToolbarEvent event) {
		// created selected item
		Administrator administrator = administratorService.createNewEntity(WorkbenchUI.getCurrent().getUser());
		
		try {
			@SuppressWarnings({ "unused", "serial" })
			WindowForm<Administrator> administratorWindow = new WindowForm<Administrator>(getI18N().getMessage("com.thingtrack.workbench.view.administrator.AdministratorView.tittle.add"), getI18N(), administrator, new AdministratorForm(), new WindowForm.CloseWindowDialogListener<Administrator>() {
				@Override
				public void windowDialogClose(WindowForm<Administrator>.CloseWindowDialogEvent<Administrator> event) {					
					if (event.getDialogResult() != WindowForm.DialogResult.OK)															
			    		return;					    		
										
					try {
						Administrator administrator = event.getDomainEntity();
						administrator.setCreatedBy(WorkbenchUI.getCurrent().getUser()); // a bug in JPA
						administrator.setCreationDate(new Date());
						
						administrator = administratorService.save(administrator);
						
						// refresh grid
						administratorContainer.addBean(administrator);
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
			});
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}			
	}
	
	@Override
	public void saveButtonClick(ClickToolbarEvent event) {
		// get selected item
		Administrator administrator = (Administrator) administratorTable.getValue();
		
		try {
			@SuppressWarnings({ "unused", "serial" })
			WindowForm<Administrator> userWindow = new WindowForm<Administrator>(getI18N().getMessage("com.thingtrack.workbench.view.administrator.AdministratorView.tittle.edit"), getI18N(), administrator, new AdministratorForm(), new WindowForm.CloseWindowDialogListener<Administrator>() {
				@Override
				public void windowDialogClose(WindowForm<Administrator>.CloseWindowDialogEvent<Administrator> event) {					
					if (event.getDialogResult() != WindowForm.DialogResult.OK)															
			    		return;					    		
										
					try {
						Administrator administrator = event.getDomainEntity();
						administrator.setUpdatedBy(WorkbenchUI.getCurrent().getUser()); // a bug in JPA
						administrator.setUpdatedDate(new Date());
						
						administrator = administratorService.save(administrator);
						
						administratorTable.refreshRowCache();
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
			});
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 		
	}
	
	@SuppressWarnings({ "unused", "rawtypes" })
	@Override
	public void removeButtonClick(ClickToolbarEvent event) {
		@SuppressWarnings("serial")
		ConfirmForm productConfirmForm = new ConfirmForm(getI18N().getMessage("com.thingtrack.workbench.view.administratorView.AdministratorView.tittle.remove"), getI18N().getMessage("com.thingtrack.workbench.view.administratorView.AdministratorView.question.remove"), new ConfirmForm.CloseConfirmFormListener() {
			@Override
			public void windowDialogClose(ConfirmForm.CloseWindowDialogEvent event) {						
				if (event.getDialogResult() != ConfirmForm.DialogResult.YES)															
		    		return;	
				
				try {
					// get selected item
					Administrator administrator = (Administrator) administratorTable.getValue();
					
					// remove item
					administrator.setActive(false);
					administratorService.save(administrator);					
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});	
	}
	
	@Override
	public void refreshButtonClick(ClickToolbarEvent event) {
		// recover register selected before refresh
		Administrator administratorSelected = (Administrator) administratorTable.getValue();

		loadDatasource(administratorPaginationToolbar.getPageNumber(), administratorPaginationToolbar.getPageSize());
								
		// select register in the grid
		if (administratorContainer.size() > 0 && administratorSelected != null)
			administratorTable.select(administratorContainer.getItem(administratorSelected));
		else if (administratorContainer.size() > 0)
			administratorTable.select(administratorContainer.getIdByIndex(0));
		
	}
	
	@Override
	public void addFilterClick(ClickToolbarEvent event) {
		loadDatasource(administratorPaginationToolbar.getPageNumber(), administratorPaginationToolbar.getPageSize());
		
	}
	
	@Override
	public void changePageSizeClick(PageEvent event) {
		loadDatasource(event.getPageNumber(), event.getPageSize());
		
	}
	
	@Override
	public void firstPageClick(PageEvent event) {
		loadDatasource(event.getPageNumber(), event.getPageSize());		
	}
	
	@Override
	public void previousPageClick(PageEvent event) {
		loadDatasource(event.getPageNumber(), event.getPageSize());
		
	}
	
	@Override
	public void nextPageClick(PageEvent event) {
		loadDatasource(event.getPageNumber(), event.getPageSize());
		
	}
	
	@Override
	public void lastPageClick(PageEvent event) {
		loadDatasource(event.getPageNumber(), event.getPageSize());
		
	}
		
	private void loadDatasource(int pageNumber, int pageSize) {
		try {
			Integer filterId = null;
			String filterName = null;
			String filterEmail = null;
			Date filterCreationDateFrom = null;
			Date filterCreationDateTo = null;
			Boolean filterActive = null;
			
			if (administratorTable.getFilterFieldValue("id") != null && !administratorTable.getFilterFieldValue("id").equals(""))
				filterId = Integer.parseInt(administratorTable.getFilterFieldValue("id").toString());
			if (administratorTable.getFilterFieldValue("name") != null && !administratorTable.getFilterFieldValue("name").equals(""))
				filterName = administratorTable.getFilterFieldValue("name").toString();
			if (administratorTable.getFilterFieldValue("email") != null && !administratorTable.getFilterFieldValue("email").equals(""))
				filterEmail = administratorTable.getFilterFieldValue("email").toString();
			if (administratorTable.getFilterFieldValue("active") != null && !administratorTable.getFilterFieldValue("active").equals(""))
				filterActive = Boolean.parseBoolean(administratorTable.getFilterFieldValue("active").toString());
			if (administratorTable.getFilterFieldValue("creationDate") != null && !administratorTable.getFilterFieldValue("creationDate").equals("")) {
				DateInterval dateInterval = (DateInterval)administratorTable.getFilterFieldValue("creationDate");
				
				filterCreationDateFrom = dateInterval.getFrom();
				filterCreationDateTo = dateInterval.getTo();
			}	
			
			// refresh count pages
			administratorPaginationToolbar.setTotPages(administratorService.getCount(administratorPaginationToolbar.getPageSize(), WorkbenchUI.getCurrent().getUser(),
					filterId, filterName, filterEmail, filterActive,
					filterCreationDateFrom, filterCreationDateTo));
			
			// select page registers			
			administrators = administratorService.getAll(pageNumber, pageSize, WorkbenchUI.getCurrent().getUser(),
					filterId, filterName, filterEmail, filterActive,
					filterCreationDateFrom, filterCreationDateTo);			

			administratorContainer.removeAllItems();
			administratorContainer.addAll(administrators);
							
			if (administratorContainer.size() > 0)
				administratorTable.select(administratorContainer.getIdByIndex(0));			
		} catch (Exception e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
}
	@Override
	protected void updateLabels() {
		if (getI18N() != null) {
			administratorTable.setColumnHeaders(new String[] { getI18N().getMessage("com.thingtrack.workbench.view.administrator.AdministratorView.administratorTable.column.id"),
					  getI18N().getMessage("com.thingtrack.workbench.view.administrator.AdministratorView.administratorTable.column.name"),
					  getI18N().getMessage("com.thingtrack.workbench.view.administrator.AdministratorView.administratorTable.column.email"),
					  getI18N().getMessage("com.thingtrack.workbench.view.administrator.AdministratorView.administratorTable.column.active"),
					  getI18N().getMessage("com.thingtrack.workbench.view.administrator.AdministratorView.administratorTable.column.creationDate")
					  });
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// administratorToolbar
		administratorToolbar = new Toolbar();
		administratorToolbar.setImmediate(false);
		administratorToolbar.setWidth("-1px");
		administratorToolbar.setHeight("-1px");
		mainLayout.addComponent(administratorToolbar);
		
		// administratorTable
		administratorTable = new FilterTable();
		administratorTable.setImmediate(true);
		administratorTable.setWidth("100.0%");
		administratorTable.setHeight("100.0%");
		mainLayout.addComponent(administratorTable);
		mainLayout.setExpandRatio(administratorTable, 1.0f);
		
		// administratorPaginationToolbar
		administratorPaginationToolbar = new PaginationToolbar();
		administratorPaginationToolbar.setImmediate(false);
		administratorPaginationToolbar.setWidth("-1px");
		administratorPaginationToolbar.setHeight("-1px");
		mainLayout.addComponent(administratorPaginationToolbar);
		mainLayout.setComponentAlignment(administratorPaginationToolbar,
				new Alignment(6));
		
		return mainLayout;
	}
}
